### ISSUE TITLE
Add integration with PlaceholderAPI plugin

### ISSUE THREAD

**Issue by SrBedrock** [DarkBlade12/SimpleAlias#11]
### Suggestion:

Add integration with the PlaceholderAPI plugin so that placeholders can be used in commands.

Example:

playtime.yml

```yml
General_Settings:
  Description: No description set
  Executable_As_Console: true
  Console_Message: This alias cannot be executed as console!
  World_Message: '&cThis alias is not enabled in your world!'
  Execution_Order:
  - cmd
  Actions:
    cmd:
      Type: MESSAGE
      Enabled_Worlds: []
      Enabled_Permission_Nodes: []
      Enabled_Permission_Groups: []
      Enabled_Params: []
      Priority: 0
      Translate_Color_Codes: false
      Message: '&a[PlayTime] &e%statistic_days_played% days!'
      Executor: SENDER
      Grant_Permission: true
      Silent: false
  Usage_Check:
    Enabled: false
    Min_Params: 0
    Max_Params: 0
    Message: '&cInvalid usage!\n&6/example'
  Permission:
    Enabled: false
    Node: armamc.staff
    Message: '&cVocê não possui acesso a este comando.'
    Groups: []
  Delay:
    Enabled: false
    Cancel_On_Move: false
    Duration: 10
    Message: '&6The alias execution will commence in &e<remaining_time>&6.'
    Cancel_Message: '&4The alias execution request was cancelled!'
  Cooldown:
    Enabled: false
    Duration: 180
    Message: '&cYou have to wait <remaining_time> until you can execute this alias
      again!'
  Cost:
    Enabled: false
    Amount: 40.0
    Message: '&cYou do not have enough money to use this alias! &8(&6<cost_amount>&8)'
  Logging:
    Enabled: false
    Message: <alias> was executed by <player_name>
  Enabled_Worlds: []
```

![image](https://user-images.githubusercontent.com/51332006/137988593-8ef0ec2a-280b-4b7a-85a1-096c65e14316.png)
